'use strict';

/**
 * Build a Chrome/Chromium (Manifest V3) package from the shared `extension/`
 * source tree, which is authored for Firefox (Manifest V2).
 *
 * Output:
 *   dist/chrome/            unpacked MV3 extension (load via chrome://extensions)
 *   dist/syncr-chrome.zip   zipped package (for the Web Store / distribution)
 *
 * The extension code is written against the `browser.*` promise API, so we
 * bundle webextension-polyfill and load it before every context:
 *   - service worker  -> background/sw.js does importScripts(polyfill, background)
 *   - content scripts -> polyfill is prepended to the js[] list
 *   - popup           -> a <script> tag for the polyfill is injected into the HTML
 *
 * A stable `key` (from extension/chrome-key.json) pins the extension ID so the
 * native-messaging host manifest's allowed_origins keeps matching.
 */

const fs   = require('fs');
const path = require('path');
const AdmZip = require('adm-zip');

const ROOT       = path.resolve(__dirname, '..');
const SRC        = path.join(ROOT, 'extension');
const DIST       = path.join(ROOT, 'dist');
const OUT        = path.join(DIST, 'chrome');
const ZIP_PATH   = path.join(DIST, 'syncr-chrome.zip');
const POLYFILL_SRC = path.join(ROOT, 'node_modules', 'webextension-polyfill', 'dist', 'browser-polyfill.min.js');
const POLYFILL_NAME = 'browser-polyfill.min.js';

// Files/dirs in extension/ that must NOT ship in the Chrome build.
const EXCLUDE = new Set(['manifest.json', 'chrome-key.json', 'web-ext-artifacts']);

function log(msg) { process.stdout.write(`[build:chrome] ${msg}\n`); }

function rmrf(p) {
  fs.rmSync(p, { recursive: true, force: true });
}

function copyTree(src, dest) {
  fs.cpSync(src, dest, {
    recursive: true,
    filter(from) {
      const rel = path.relative(src, from);
      if (!rel) return true;
      const top = rel.split(path.sep)[0];
      if (top.startsWith('.')) return false;
      return !EXCLUDE.has(top);
    },
  });
}

function main() {
  // --- Read source manifest + stable key -----------------------------------
  const mv2 = JSON.parse(fs.readFileSync(path.join(SRC, 'manifest.json'), 'utf8'));

  const keyPath = path.join(SRC, 'chrome-key.json');
  if (!fs.existsSync(keyPath)) {
    throw new Error('extension/chrome-key.json missing — run scripts/gen-chrome-key.js first.');
  }
  const { key, extensionId } = JSON.parse(fs.readFileSync(keyPath, 'utf8'));
  if (!key) throw new Error('chrome-key.json has no "key" field.');

  if (!fs.existsSync(POLYFILL_SRC)) {
    throw new Error('webextension-polyfill not installed — run `npm install` at the repo root.');
  }

  const iconDir = path.join(SRC, 'icons');
  for (const size of [16, 32, 48, 128]) {
    if (!fs.existsSync(path.join(iconDir, `icon-${size}.png`))) {
      throw new Error(`Missing PNG icon icons/icon-${size}.png (Chrome cannot use SVG manifest icons).`);
    }
  }

  // --- Fresh output tree ---------------------------------------------------
  log('preparing dist/chrome …');
  rmrf(OUT);
  fs.mkdirSync(OUT, { recursive: true });
  copyTree(SRC, OUT);

  // --- Bundle the polyfill -------------------------------------------------
  fs.copyFileSync(POLYFILL_SRC, path.join(OUT, POLYFILL_NAME));

  // --- Service worker entry ------------------------------------------------
  const swDir = path.join(OUT, 'background');
  fs.mkdirSync(swDir, { recursive: true });
  fs.writeFileSync(
    path.join(swDir, 'sw.js'),
    `'use strict';\n` +
    `// Chrome MV3 service worker entry — generated by scripts/build-chrome.js.\n` +
    `// Loads the WebExtension API polyfill, then the shared background logic.\n` +
    `importScripts('/${POLYFILL_NAME}', '/background/background.js');\n`,
  );

  // --- Content scripts: prepend the polyfill -------------------------------
  const contentScripts = (mv2.content_scripts || []).map(cs => ({
    ...cs,
    js: [POLYFILL_NAME, ...(cs.js || [])],
  }));

  const icons = { 16: 'icons/icon-16.png', 32: 'icons/icon-32.png', 48: 'icons/icon-48.png', 128: 'icons/icon-128.png' };

  // --- Build the MV3 manifest ----------------------------------------------
  const mv3 = {
    manifest_version: 3,
    name: mv2.name,
    version: mv2.version,
    description: mv2.description.replace(/\bin Firefox\b/i, 'in your browser'),
    author: mv2.author,
    key,
    icons,
    action: {
      default_popup: mv2.browser_action.default_popup,
      default_title: mv2.browser_action.default_title,
      default_icon: icons,
    },
    background: {
      service_worker: 'background/sw.js',
    },
    content_scripts: contentScripts,
    permissions: (mv2.permissions || []).filter(p => !p.includes('://') && p !== '<all_urls>'),
    host_permissions: ['*://*/*'],
    web_accessible_resources: [
      {
        resources: mv2.web_accessible_resources || [],
        matches: ['<all_urls>'],
      },
    ],
  };

  fs.writeFileSync(path.join(OUT, 'manifest.json'), JSON.stringify(mv3, null, 2) + '\n');

  // --- Inject the polyfill into the popup HTML -----------------------------
  const popupHtmlPath = path.join(OUT, 'popup', 'popup.html');
  if (fs.existsSync(popupHtmlPath)) {
    let html = fs.readFileSync(popupHtmlPath, 'utf8');
    const tag = `<script src="../${POLYFILL_NAME}"></script>`;
    if (!html.includes(tag)) {
      html = html.replace(
        /<script\s+src="popup\.js"><\/script>/,
        `${tag}\n<script src="popup.js"></script>`,
      );
    }
    fs.writeFileSync(popupHtmlPath, html);
  }

  // --- Zip -----------------------------------------------------------------
  log('zipping …');
  rmrf(ZIP_PATH);
  const zip = new AdmZip();
  zip.addLocalFolder(OUT);
  zip.writeZip(ZIP_PATH);

  log(`extension ID : ${extensionId || '(unknown)'}`);
  log(`unpacked     : ${path.relative(ROOT, OUT)}`);
  log(`package      : ${path.relative(ROOT, ZIP_PATH)}`);
  log('done.');
}

main();
